version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
     - ./docker_volumes/redis:/usr/share/redis/data
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
