FROM python:3.11-slim-bookworm

WORKDIR /app

# Копируем requirements
COPY ./requirements.txt ./requirements.txt

# Устанавливаем зависимости
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Копируем весь проект (backend И celery_service)
COPY . /app

# Устанавливаем PYTHONPATH
ENV PYTHONPATH=/app

# Рабочая директория остаётся /app
WORKDIR /app
